config/routes.rb
Rails.application.routes.draw do
  root 'markets#index', as: :markets_index
  get '/markets/:id', to:'markets#show', as: :markets_show
  get '/markets/:id/payment', to:'markets#payment', as: :payment
  post '/markets/:id/payment', to:'markets#payment_process', as: :payment_process

  namespace :users do
    resources :products

    resource :profiles, except: [:index, :create]
  end

  get '/users/sign_up', to: 'users#sign_up', as: :sign_up
  post '/users/sign_up', to: 'users#sign_up_process', as: :sign_up_process
  get '/users/sign_in', to: 'users#sign_in', as: :sign_in
  post '/users/sign_in', to: 'users#sign_in_process', as: :sign_in_process
  get '/users/sign_out', to: 'users#sign_out', as: :sign_out
  get '/users/likes', to: 'users#show', as: :favorites
  get '/users/:id/likes', to: 'users#create', as: :create_favorite

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)      not null
#  image           :string(255)
#  profile         :text(65535)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  mount_uploader :image, UserImageUploader

  has_many :products, dependent: :destroy
  has_many :user_likes, dependent: :destroy

  #bcrypt
  has_secure_password

  #バリデーション
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  # sign_up_processの時のみpresenceをtrueにする。sign_in_processはpasswordのみtrueに。
  validates :password, presence: true, on: :sign_up_process, on: :sign_in_process
  validates :password_confirmation, presence: true, on: :sign_up_process
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  #新規出品ページ
  def new
    if current_user.nil?
      redirect_to sign_in_path
    else
      @product = Product.new
    end
  end

  #新規出品する
  def create
    @product = current_user.products.build(product_params)
      if @product.save
        redirect_to users_products_path, flash: { notice: "出品しました！"}
      else
        flash[:danger] = "出品できませんでした"
        render "new" and return
      end
  end

  #ユーザーのproducts
  def index
    # Product modelからuserがcurrent_userであるものを取得する。
    # findはid以外での検索はRails4で廃止された。
    @products = Product.where(user: current_user)
  end

  #userのproduct詳細
  #現在ログインしているUserの指定されたProductの詳細を表示する。
  def show
    @product = current_user.products.find(params[:id])
    #販売手数料(margin)と販売利益(profit)を計算し、切り捨てで表示する。
    @margin = (@product.price * 0.1).floor
    @profit = @product.price - @margin
  end

  #userのproduct編集画面
  def edit
    @product = current_user.products.find(params[:id])
  end

  #userのproduct編集プロセス。
  def update
    @product = current_user.products.find(params[:id])

    @product.update(product_params)
    redirect_to users_product_path(@product) and return
  end

  #userのproduct削除
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:success] = "商品を削除しました。"
      redirect_to users_products_path and return
    else
      flash[:danger] = "削除できませんでした。"
      render "index" and return
    end
  end

  private
  def product_params
    params.require(:product).permit(:id, :name, :description, :price, :category_id, :image1, :image2, :image3, :status)
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  #プロフィールページトップ
  def show
    if current_user.nil?
      redirect_to sign_in_path
    else
      @user = User.find(current_user.id)
    end
  end

  #プロフィール編集
  def edit
    @user = User.find(current_user.id)
  end

  #プロフィール更新処理
  def update
    current_user.update(user_params)
    redirect_to users_profiles_path and return
  end

  private
  def user_params
    params.require(:user).permit(:id, :name, :email, :profile, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:sign_up, :sign_up_process, :sign_in, :sign_in_process]
  before_action :redirect_to_top_if_already_signed_in, only: [:sign_up, :sign_in]

  #新規登録
  def sign_up
    @user = User.new
  end

  #登録処理
  def sign_up_process
    @user = User.new(user_params)
    if @user.save
      # セッション処理.登録が完了したらサインインしてトップページへ
      user_sign_in(@user)
      redirect_to users_profiles_path, flash: { notice: "登録が完了しました" }
    else
      #登録失敗
      render "sign_up" and return
    end
  end

  #ログイン
  def sign_in
    @user = User.new
  end

  #ログイン処理
  def sign_in_process
    @user = User.new
    #メールアドレスでユーザーを検索
    user = User.find_by(email: user_params[:email])
    #パスワードの一致を検証
    if user && user.authenticate(user_params[:password])
      user_sign_in(user)
      redirect_to users_profiles_path, flash: { notice: "ログインに成功しました" }
    else
      flash[:danger] = "ログインに失敗しました"
      render "sign_in" and return
    end
  end

  #サインアウト
  def sign_out
    #セッションを破棄
    user_sign_out
    #サインインページへ遷移
    redirect_to sign_in_path and return
  end

  #商品をお気に入りにする
  def create
    @product = Product.find(params[:id])
    #その商品をお気に入りにしていたら解除、していなかったらCreateする。
    if UserLike.exists?(product_id: @product.id, user_id: current_user.id)
      UserLike.find_by(product_id: @product.id, user_id: current_user.id).destroy
    else
      UserLike.create(product_id: @product.id, user_id: current_user.id)
    end
    redirect_to markets_index_path and return
  end

  #お気に入り商品を表示
  def show
    #UserLikeモデルからuser_idでcurrent_userのUserLikeモデルを配列で受け取る。
    @user_likes = UserLike.where(user_id: current_user.id)
    #eachの中で追加するために、@productsを空の配列として宣言。
    @products = []
    #69行目で取得した配列からUserLikeモデルを1つずつeachで処理する。
    @user_likes.each do |user_like|
      #取得した1件のUserLikeモデルからproductを取り出して、@products配列に追加する。
      @products << user_like.product
    end
  end

  private
  def user_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/users/products_helper.rb
module Users::ProductsHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 渡されたユーザーでサインインする
  def user_sign_in(user)
    session[:user_id] = user.id
  end
  #サインアウトする。ログインしているユーザーのセッションを削除する。
  def user_sign_out
    session.delete(:user_id)
    @current_user = nil
  end

  #user signed_in>>true, doesn't sign_in>>false
  def user_signed_in?
    current_user.present?
  end

  #current_userのidがnilだった場合、セッションのidを付与する。
  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  #認証チェック。サインインしてなければサインインページにリダイレクトする。
  def authorize
    redirect_to sign_in_path unless user_signed_in?
  end

  #if user has signed in, redirect him/her to top page.
  def redirect_to_top_if_already_signed_in
    redirect_to list_path and return if user_signed_in?
  end

  #profileページのuser iconがなければダミーを使い、データがあればuploads/user/から使用する。
  def user_image_url(user)
    if user.image.present?
      image_tag user.image_url
    else
      image_tag "https://placehold.it/200x200/?text=no user's picture"
    end
  end

  #user signed in=> profile page, user not sign in =>sign in sign in page
  def redirect_user
    if user_signed_in?
      redirect_to users_profiles_path and return
    else
      redirect_to sign_in_path and return
    end
  end
end

app/views/users/_my_menu.html.erb
<div class="menu_container">
  <h1>マイページ</h1>
  <ul class="my_menus">
    <li><%= link_to "出品する", new_users_product_path %></li>
    <li><%= link_to "出品中の商品", users_products_path %></li>
    <li><%= link_to "お気に入り商品", favorites_path %></li>
    <li><%= link_to "プロフィール編集", edit_users_profiles_path %></li>
    <li><%= link_to "サインアウト", sign_out_path %></li>
  </ul>
</div>

app/views/users/_search_menu.html.erb
<div class="search_menu_container">
  <h1>詳細検索</h1>
  <div class="search_menu">
    <%= form_tag(markets_index_path, method: :get) do %>
      <div class="keyword_wrap">
        <!-- nilを入れないとplaceholderがvalueの位置に入ってしまう -->
        <%= label_tag :キーワード検索 %>
        <%= text_field_tag :keyword, nil, placeholder: "例：値上げ" %>
      </div>
      <div class="category_wrap">
        <%= label_tag :カテゴリー検索 %>
        <%= collection_select Category, :category_id, Category.all, :id, :name, :include_blank => ""  %>
      </div>
      <div class="price_wrap">
        <%= label_tag :価格検索 %><br>
        <%= text_field_tag :mini_price, nil, placeholder: '100' %>~
        <%= text_field_tag :max_price, nil, placeholder: '1000' %>
      </div>
      <div class="order_wrap">
        <%= label_tag :並べ替え %><br>
        <%= select :order, :status, [["値段が安い順", "price_order_ascend"], ["値段が高い順", "price_order_descend"], ["新しい順", "created_at_descend"], ["古い順", "created_at_ascend"]], :include_blank => "" %>
      </div>
      <!-- 出品中、売切をselectでソート-->
      <div class="status_wrap">
        <%= label_tag :商品ステータス選択 %><br>
        <%= select :sort, :status, [["出品中", "selling"], ["売切", "soldout"]], :include_blank => "" %>
      </div>
      <div class="btn_wrap">
        <%= submit_tag value="検索" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="page-container">
  <% if @products.any? %>
  <section class="items-box-container">
  <% @products.each do |product| %>
    <div class="items-box-content">
      <%= link_to markets_show_path(product) do %>
      <div class="items-box-photo">
        <%= image_tag product.image1_url %>
      </div>
      <% end %>
      <div class="items-box-body">
        <h3><%= product.name %></h3>
        <p class="items-box-price">\<%= number_with_delimiter(product.price) %></p>
        <p class="items-box-tax">(税込)</p>
        <div class="items-box-favorite">
          <%= link_to create_favorite_path(product) do %>
          <i class="fa <%= product.favorite?(current_user)? "fa-star": "fa-star-o" %>"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% else %>
  <p class="empty">お気に入りはありません。</p>
  <% end %>
  </section>
    <%= render partial: 'my_menu', locals: {user: @user} %>
</div>

app/views/users/sign_in.html.erb
<div class="page-container">
  <div class="sign-in-container">
    <%= form_for(@user, url: {controller: :users, action: :sign_in_process}) do |f| %>
      <div class="user_email_wrap">
        <%= f.label :email, "メールアドレス" %><br>
        <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
      <div class="user_password_wrap">
        <%= f.label :email, "パスワード" %><br>
        <%= f.password_field :password, placeholder: "８文字以上の英数字" %>
      </div>
      <div class="user_btn_wrap">
        <%= f.submit "サインインする" %>
      </div>
    <% end %>
    <%= link_to sign_up_path do %>
      <p>新規登録はこちらから</p>
    <% end %>
  </div>
  <%= render partial: 'search_menu' %>
</div>

app/views/users/sign_up.html.erb
<div class="page-container">
  <div class="sign-up-container">
    <%= form_for @user, url: sign_up_path do |f| %>
      <% if @user.errors.any? %>
        <ul class="errors">
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="field">
        <label>ニックネーム</label><br>
        <%= f.text_field :name, placeholder: "五木ひろし" %>
      </div>
      <div class="field">
        <label>メールアドレス</label><br>
        <%= f.email_field :email, placeholder: "メールアドレス" %>
      </div>
      <div class="field">
        <label>パスワード</label><br>
        <%= f.password_field :password, placeholder: "８文字以上の英数字" %>
      </div>
      <div class="field">
        <label>パスワード（確認用）</label><br>
        <%= f.password_field :password_confirmation, placeholder: "確認用" %>
      </div>
      <div class="user_btn_wrap">
        <%= f.submit "新規登録する" %>
      </div>
    <% end %>
    <%= link_to sign_in_path do %>
      <p>アカウントをお持ちの方はこちらへ</p>
    <% end %>
  </div>
  <%= render partial: 'search_menu' %>
</div>