config/routes.rb
Rails.application.routes.draw do
  root 'markets#index', as: :markets_index
  get '/markets/:id', to:'markets#show', as: :markets_show
  get '/markets/:id/payment', to:'markets#payment', as: :payment
  post '/markets/:id/payment', to:'markets#payment_process', as: :payment_process

  namespace :users do
    resources :products

    resource :profiles, except: [:index, :create]
  end

  get '/users/sign_up', to: 'users#sign_up', as: :sign_up
  post '/users/sign_up', to: 'users#sign_up_process', as: :sign_up_process
  get '/users/sign_in', to: 'users#sign_in', as: :sign_in
  post '/users/sign_in', to: 'users#sign_in_process', as: :sign_in_process
  get '/users/sign_out', to: 'users#sign_out', as: :sign_out
  get '/users/likes', to: 'users#show', as: :favorites
  get '/users/:id/likes', to: 'users#create', as: :create_favorite

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Market</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>
  <body class="default">
    <header class="global_header">
      <div class="header-wrap">
        <%= link_to markets_index_path do %>
        <h1 class="logo">CodeC<span>a</span>mp Market</h1>
        <% end %>
        <!-- 検索フォーム -->
        <form class="search">
          <input type="text" placeholder="キーワード検索" name="word" value="">
        </form>
        <!-- メニュー -->
        <ul class="menu">
          <li class="button">
            <!-- 出品 -->
            <%= link_to new_users_product_path do %>
              <input type="submit" value="出品する" class="button">
            <% end %>
          </li>
          <li class="profile">
            <!-- プロフィールページ -->
            <!-- 現在のUserのProfileを見るだけの為、paramsは渡さなくてもSessionidで認識している -->
            <%= link_to users_profiles_path do %>
              <i class="fa fa-address-card">
                <p>マイページ</p>
              </i>
            <% end %>
          </li>
        </ul>
      </div>
    </header>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        window.setTimeout(function() {
            $(".alert").slideUp();
        }, 3000);
    </script>
    <footer class="global_footer">
      <ul class="footer_menu">
        <li>プライバシーポリシー</li>
        <li>特定商取引に基づく表示</li>
        <li>利用規約</li>
        <li>サイトマップ</li>
      </ul>
    </footer>
  </body>
</html>